package p69;
/*
  message : test2
  name : James Kim
  content : github test7
*/
public class SignOperatorExample {
	public static void main(String[] args) {
		// comment : 1...
		// comment : 2...
		// comment : 3...
		// comment : 4...
		// comment : 5...
		// comment : 6...
		// comment : 7...
	}
}
